# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "release/wsf" ]
  pull_request:
    branches: [ "release/wsf" ]

env:
  PIGDIG_KEY: ${{ secrets.PIGDIG_KEY }}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@0609f0983b7a228f052f81ef4c3d6510cae254ad
      with:
        version: 6.10.0
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
    - run: pnpm install
    - run: pnpm build
    - name: Publish
      uses: nogsantos/scp-deploy@master
      with:
        src: ./dist/*
        host: pig-dig.cn
        remote: /data/pig-dig-dist/
        prot: 22
        user: root
        key: ${{ env.PIGDIG_KEY }}